language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/jpm
before_install:
  - chmod +x install-jpm.sh
  - bash install-jpm.sh
after_script:
  - mvn clean install -Pcodacy
  - $HOME/jpm/bin/codacy-coverage-reporter -l Java -r $JACOCO_REPORT_FILE
